### ISSUE TITLE
[Question] Why using the Pages router over the App route?

### ISSUE THREAD

**Issue by olivierobert** [shahriar-ratul/test-web-keyword#1]
Since the application is built with Next.JS > 12, the codebase could have been structured using the newer [App Router](https://nextjs.org/docs/app). So why pick the [Pages router](https://nextjs.org/docs/pages/building-your-application) over the newer router? 

Both approaches are valid. I am interested in understanding your decision-making process when you approached the technical challenge 🧠

**Comment by shahriar-ratul** [comment]
Hello olivierobert,
I choose pages because i worked all of my previous projects on pages routes.
i learned about pages routes but as i haven't applied in real projects. so i pick pages over app router.

**Comment by olivierobert** [comment]
Understood :-) The migration to the App router is not that complex (we did it internally 😉 ) as the same file-based conventions work out of the box. The only harder part is getting used to adding `use client` and `use server` for each route.
